name:                hnefatafl
version:             0.1.0.0
github:              "Shteevee/hnefatafl"
license:             BSD3
author:              "Shteevee"
maintainer:          "Shteevee"
copyright:           "2022 Shteevee"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Shteevee/hnefatafl#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hnefatafl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnefatafl

tests:
  hnefatafl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hnefatafl
